language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

before_deploy: "echo 'Deploying to nautilusdev.com s3 bucket'"

deploy:
  provider: s3
  access_key_id: "AKIA5BE74LB4NXABBGHB"
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: "nautilusdev.com"
  acl: public_read
  skip_cleanup: true
  region: us-west-1
  local_dir: build

branches:
  only:
    - master
